services:
  backend:
    build: ./backend
    container_name: task_manager_backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      PORT: 4000
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: 
     context : ./frontend
    container_name: task_manager_frontend
    depends_on:
    - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      NEXT_PUBLIC_BACKEND_URL: http://host.docker.internal:4000/api
    volumes:
      - ./frontend/.env.local:/app/.env.local
    
 

    command: npm run dev
