apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
data:
  # Base64-encoded values
  # Replace the base64 value below with base64(MONGO_URI). Example:
  # echo -n "mongodb+srv://user:pass@cluster0.../task_manager" | base64
  MONGO_URI: bW9uZ29kYitzcnY6Ly9rcmlzaG5hc2hha3lhNzI3MjpTaGFkY25VSUBzaGFkY251aS5laWVlaGRoLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1TaGFkY25VSQ==
