apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
data:
  # Base64-encoded values
  # echo -n "mongodb+srv://user:pass@cluster0.../task_manager" | base64
  MONGO_URI: bW9uZ29kYitzcnY6Ly9rcmlzaG5hc2hha3lhNzI3MjpTaGFkY25VSUBzaGFkY251aS5laWVlaGRoLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1TaGFkY25VSQ==
  JWT_SECRET: c3VwZXJzZWNyZXQ=
  GOOGLE_CLIENT_ID: MzM1MTQ1NzQ5MTk1LW44ZW0wazlhdXEybW9jNnVhMHJlcHMzODY3ZWgwcWpqLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t