apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  labels:
    app: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - name: backend
      port: 4000
      targetPort: 4000
      protocol: TCP
    - name: frontend
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
